<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-11-29 20:38
=======
# Generated by Django 5.2.1 on 2025-12-11 03:14
>>>>>>> remotes/origin/90/ajustes-finais-documentação

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pics/', verbose_name='Foto de Perfil'),
        ),
    ]
