# Generated by Django 5.2.1 on 2025-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/imgs/default-profile-picture.png', null=True, upload_to='uploads/profile_pics/', verbose_name='Foto de Perfil'),
        ),
    ]
