# Generated by Django 5.2.1 on 2026-01-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
        ('users', '0002_fix_default_profile_picture'),
    ]

    operations = [
    ]
