# Generated by Django 5.2.1 on 2025-07-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cep', models.CharField(max_length=9)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('address_complement', models.CharField(max_length=50)),
                ('enterprise', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.enterprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
