# Generated by Django 5.2.1 on 2025-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='address_complement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
