# Generated by Django 5.2.1 on 2025-07-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_authuser_address_complement_and_more'),
        ('enterprise', '0002_alter_enterprise_address_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='enterprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.enterprise'),
        ),
    ]
