# Generated by Django 5.2.1 on 2025-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_authuser_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='address_complement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
