# Generated by Django 5.2.1 on 2025-07-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
                ('type', models.CharField(choices=[('Fixo', 'Fixo'), ('Móvel', 'Movel')])),
                ('main_number', models.BooleanField()),
                ('auth_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_user.authuser')),
            ],
        ),
    ]
