# Generated by Django 5.2.1 on 2025-07-08 22:44

import apps.core.services.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, validators=[apps.core.services.validators.ValidatorService.is_valid_cep], verbose_name='CEP')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RN', max_length=2, verbose_name='Estado')),
                ('city', models.CharField(max_length=75, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=75, verbose_name='Bairro')),
                ('street_name', models.CharField(max_length=75, verbose_name='Nome da Rua')),
                ('number', models.CharField(max_length=5, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=75, null=True, verbose_name='Complemento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['street_name', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[apps.core.services.validators.ValidatorService.is_valid_phone], verbose_name='Número de Telefone')),
                ('phone_type', models.CharField(choices=[('Mobile', 'Celular'), ('Landline', 'Fixo'), ('WhatsApp', 'WhatsApp'), ('Other', 'Outro')], default='Mobile', max_length=20, verbose_name='Tipo de Telefone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
                'ordering': ['phone_number'],
                'unique_together': {('phone_number', 'phone_type')},
            },
        ),
    ]
