# Generated by Django 5.2.1 on 2025-11-03 12:26

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, default='static/imgs/default-offer-image.png', null=True, upload_to='uploads/offers/', verbose_name='Imagem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Expiração')),
                ('redemption_period', models.DurationField(default=datetime.timedelta(days=30), verbose_name='Período de Resgate')),
                ('max_coupons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade máxima')),
                ('generated_coupons', models.IntegerField(default=0, verbose_name='Cupons gerados')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offer.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-start_date'],
            },
        ),
    ]
