# Generated by Django 5.2.1 on 2025-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='enterprise.enterprise', verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('title', 'enterprise')},
        ),
    ]
