# Generated by Django 5.2.1 on 2026-01-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_fix_default_image'),
        ('offer', '0002_initial'),
    ]

    operations = [
    ]
