# Generated by Django 5.2.1 on 2025-07-31 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='generated_coupons',
            field=models.IntegerField(default=0, verbose_name='Cupons gerados'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_coupons',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade máxima'),
        ),
    ]
