# Generated by Django 5.2.1 on 2025-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('offer', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('title', 'enterprise'), name='uniq_enterprise_title'),
        ),
    ]
