# Generated by Django 5.2.1 on 2025-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_delete_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Imagem'),
        ),
    ]
