# Generated by Django 5.2.1 on 2025-10-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_unique_together_and_more'),
        ('offer', '0004_delete_evaluation'),
    ]

    operations = [
    ]
