# Generated by Django 5.2.1 on 2025-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_merge_20251008_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='static/imgs/default-offer-image.png', null=True, upload_to='uploads/offers/', verbose_name='Imagem'),
        ),
    ]
