# Generated by Django 5.2.1 on 2026-01-18 22:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Estrelas",
                    ),
                ),
                ("message", models.CharField(max_length=300, verbose_name="Mensagem")),
            ],
            options={
                "verbose_name": "Avaliação de Cupom",
                "verbose_name_plural": "Avaliações de Cupons",
                "ordering": ["coupon", "-stars"],
            },
        ),
    ]
