# Generated by Django 5.2.1 on 2025-07-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
        ('subscription_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_user.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('active', models.BooleanField()),
                ('subscriber', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriber.subscriber')),
                ('subscription_plan', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription_plan.subscriptionplan')),
            ],
        ),
    ]
