# Generated by Django 5.2.1 on 2025-09-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
        ('subscription', '0003_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='active_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_subscriber', to='subscription.subscription', verbose_name='Assinatura Ativa'),
        ),
    ]
