# Generated by Django 5.2.1 on 2026-01-18 22:05

import apps.core.services.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coupon", "0002_initial"),
        ("subscriber", "0001_initial"),
        ("subscription", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="coupon",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Reviews",
                to="coupon.coupon",
                verbose_name="Cupom",
            ),
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="subscriber",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Sobrenome"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            apps.core.services.validators.ValidatorService.is_valid_cpf
                        ],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "active_subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_for_subscriber",
                        to="subscription.subscription",
                        verbose_name="Assinatura Ativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinante",
                "verbose_name_plural": "Assinantes",
                "ordering": ["user__email"],
            },
        ),
    ]
