# Generated by Django 5.2.1 on 2025-09-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_remove_subscriber_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
