# Generated by Django 5.2.1 on 2025-09-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_subscriber_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
