# Generated by Django 5.2.1 on 2025-08-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_feature_subscriptionplan_features"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={
                "ordering": ["name"],
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="duration",
            field=models.DurationField(verbose_name="Duração em dias"),
        ),
    ]
