# Generated by Django 5.2.1 on 2025-09-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
    ]
