# Generated by Django 5.2.1 on 2025-08-04 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Resgate')),
                ('expiration_date', models.DateTimeField(verbose_name='Data de Expiração do Cupom')),
                ('used_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de Uso')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-creation_date'],
            },
        ),
    ]
