# Generated by Django 5.2.1 on 2025-09-29 00:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0004_delete_evaluation'),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Resgate')),
                ('expiration_date', models.DateTimeField(verbose_name='Data de Expiração do Cupom')),
                ('used_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de Uso')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='offer.offer', verbose_name='Oferta')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='subscriber.subscriber', verbose_name='Assinante')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-creation_date'],
                'unique_together': {('subscriber', 'offer')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Estrelas')),
                ('message', models.CharField(max_length=300, verbose_name='Mensagem')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='coupon.coupon', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['coupon', 'stars'],
            },
        ),
    ]
