# Generated by Django 5.2.1 on 2025-07-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('offer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.offer')),
                ('subscriber', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriber.subscriber')),
            ],
        ),
    ]
