# Generated by Django 5.2.1 on 2026-01-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coupon", "0001_initial"),
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="offer.offer",
                verbose_name="Oferta",
            ),
        ),
    ]
