# Generated by Django 5.2.1 on 2025-08-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0002_initial'),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='subscriber.subscriber', verbose_name='Assinante'),
        ),
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('subscriber', 'offer')},
        ),
    ]
