# Generated by Django 5.2.1 on 2026-01-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_code_unique'),
        ('coupon', '0003_initial'),
    ]

    operations = [
    ]
