# Generated by Django 5.2.1 on 2026-01-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_expiration_nullable'),
        ('coupon', '0004_merge_0002_alter_code_unique_0003_initial'),
    ]

    operations = [
    ]
