# Generated by Django 5.2.1 on 2025-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=50)),
                ('corporate_reason', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=9)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('address_complement', models.CharField(max_length=50)),
                ('operation_areas', models.ManyToManyField(to='enterprise.operationarea')),
            ],
        ),
    ]
