# Generated by Django 5.2.1 on 2025-11-03 10:47

import apps.core.services.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do ramo')),
            ],
            options={
                'verbose_name': 'Ramo de Atividade',
                'verbose_name_plural': 'Ramos de Atividade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enterprise', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('corporate_reason', models.CharField(max_length=200, unique=True, verbose_name='Razão Social')),
                ('trade_name', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[apps.core.services.validators.ValidatorService.is_valid_cnpj], verbose_name='CNPJ')),
                ('line_of_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='enterprise.lineofbusiness', verbose_name='Ramo de Atividade')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['trade_name'],
            },
        ),
    ]
