# Generated by Django 5.2.1 on 2025-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_enterprise_address_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='address_complement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
