# Generated by Django 5.2.3 on 2025-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUsuario', models.CharField(max_length=200)),
                ('logradouro', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('bairro', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=130)),
                ('cidade', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=8)),
                ('razaoSocial', models.CharField(max_length=80, null=True)),
                ('cnpj', models.CharField(max_length=15, null=True)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('dataNascimento', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
